AllCops:
  RunRailsCops: true
  Exclude:
    - bin/**/*
    - db/**/*
    - test/**/*
    - spec/**/*
# Main style rules
# ================

# Relax some limits
Metrics/LineLength:
  Max: 150

# Disabel class level comments
Style/Documentation:
  Enabled: false
