language: ruby
cache: bundler

before_install:
  - sudo apt-get install aspell libaspell-dev aspell-en aspell-de
  - sudo apt-get install sphinxsearch

before_script:
  - mysql -e 'create database katalog_test'
  - DB=mysql bundle exec rake katalog:setup
  - DB=mysql bundle exec rake db:create db:schema:load
  - bundle exec rake katalog:ts:export_lists ts:rebuild katalog:raspell:update

script: "bundle exec rake spec"

# whitelist
branches:
  only:
    - master
    - staging
    - stable

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
