language: ruby
cache: bundler

before_script:
  - sudo apt-get install aspell libaspell-dev aspell-en aspell-de
  - which aspell
  - bundle config build.raspell --with-opt-dir= && bundle install
  - "mysql -e 'create database katalog_test;'"
  - DB=mysql bundle exec rake katalog:setup
  - DB=mysql bundle exec rake db:create db:schema:load

script: "bundle exec rake spec"

# whitelist
branches:
  only:
    - master
    - staging
    - stable

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
