env: "RAILS_ENV='test'"
before_script:
  - "mysql -e 'create database katalog_test;' >/dev/null"
  - bundle exec rake katalog:setup
  - bundle exec rake db:create db:schema:load
script: "bundle exec rake test"

